services:
  landing:
    build:
      context: ./landing-page
    container_name: landing
    working_dir: /app
    volumes:
      - ./landing-page:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev

  chat:
    build:
      context: ./chat-page
    container_name: chat
    working_dir: /app
    volumes:
      - ./chat-page:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"
    command: npm run dev