import { ProjectState } from '../pipeline/types';
import { db } from '../firebase-admin';
import { callGroqRaw, createCallConfig } from '../pipeline/GroqClient';

export async function exportToCalendar(
  state: ProjectState,
  title: string,
  userId: string,
  accessToken: string,
  logSummary: any,
  onProgress: (msg: string) => Promise<void>
) {
  try {
    await onProgress('Analyzing timeline for calendar events...');

    const prompt = `
You are an AI assistant. I need you to parse the following project timeline and roadmap into a JSON array of calendar events.
Project Title: ${title}

TIMELINE:
${state.artifacts['projectTimeline']?.content || 'No timeline provided'}

ROADMAP:
${state.artifacts['roadmap']?.content || 'No roadmap provided'}

Return ONLY a JSON array with objects in this format:
[
  {
    "summary": "Event Title (e.g., Phase 1: Foundation, or Sprint Planning, or Demo)",
    "description": "Brief description of the event, deliverables or goals.",
    "startOffsetDays": 0, // Number of days from today this event starts
    "endOffsetDays": 7   // Number of days from today this event ends
  }
]
No markdown wrapping, just the raw JSON array.
`;

    const groqKey = process.env.GROQ_API_KEY;
    if (!groqKey) throw new Error('GROQ_API_KEY is not set');

    const config = createCallConfig(groqKey, 1024, 0.2);
    const res = await callGroqRaw(
      config,
      [{ role: 'user', content: prompt }],
      'GenerateCalendarDraft'
    );

    if (!res || !res.content) throw new Error(`Groq API error`);
    const rawOutput = res.content;
    
    let events = [];
    try {
      events = JSON.parse(rawOutput);
    } catch (e) {
      console.error('Failed to parse Gemini output:', rawOutput);
      throw new Error('Failed to parse calendar events from AI output.');
    }

    if (!Array.isArray(events) || events.length === 0) {
      throw new Error('No events generated by AI.');
    }

    await onProgress(`Generated ${events.length} events. Syncing to Google Calendar...`);

    const now = new Date();
    const createdEventIds: string[] = [];
    
    // Check for existing event IDs
    const userRef = db.collection('user_integrations').doc(userId);
    const userDoc = await userRef.get();
    const existingEvents = userDoc.data()?.googleCalendar?.eventIds || [];

    for (let i = 0; i < events.length; i++) {
      const ev = events[i];
      const startDate = new Date(now.getTime() + ev.startOffsetDays * 24 * 60 * 60 * 1000);
      const endDate = new Date(now.getTime() + ev.endOffsetDays * 24 * 60 * 60 * 1000);

      const eventBody = {
        summary: ev.summary,
        description: ev.description,
        start: { date: startDate.toISOString().split('T')[0] },
        end: { date: endDate.toISOString().split('T')[0] }
      };

      let url = 'https://www.googleapis.com/calendar/v3/calendars/primary/events';
      let method = 'POST';

      if (existingEvents[i]) {
        url = `https://www.googleapis.com/calendar/v3/calendars/primary/events/${existingEvents[i]}`;
        method = 'PUT';
      }

      const calRes = await fetch(url, {
        method,
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(eventBody)
      });

      if (!calRes.ok) {
        console.error(`Failed to create/update event: ${ev.summary}`, await calRes.text());
        continue;
      }

      const calData = await calRes.json();
      if (calData.id && method === 'POST') {
        createdEventIds.push(calData.id);
      } else if (method === 'PUT') {
        createdEventIds.push(existingEvents[i]);
      }
    }

    if (createdEventIds.length > 0) {
      await userRef.set({
        googleCalendar: {
          eventIds: createdEventIds,
          updatedAt: new Date().toISOString()
        }
      }, { merge: true });
    }

    return {
      calendarUrl: 'https://calendar.google.com',
      eventsCreated: createdEventIds.length
    };
  } catch (error: any) {
    console.error('Calendar export error:', error);
    return null;
  }
}
