import { getGithubClient } from './client';
import type { ProjectState, ArtifactType } from '@/lib/pipeline/types';

function toKebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '');
}

function getCategorizedPath(artifactType: string, baseName: string): string {
  const categoryMap: Record<string, string> = {
    markdown: '',
    folderStructure: 'architecture',
    architecture: 'architecture',
    apiDesign: 'api',
    db: 'database',
    docker: 'deployment',
    deploymentGuide: 'deployment',
    roadmap: 'planning',
    projectTimeline: 'planning',
    costEstimation: 'planning',
    riskAnalysis: 'planning',
    userStories: 'planning',
    testingPlan: 'planning',
  };

  const category = categoryMap[artifactType] || 'misc';
  if (category === '') return `docs/${baseName}.md`;
  return `docs/${category}/${baseName}.md`;
}

function getFileNameForArtifact(artifactType: ArtifactType): string {
  const names: Record<ArtifactType, string> = {
    config: 'project-config',
    markdown: 'README',
    db: 'database-schema',
    apiDesign: 'api-design',
    folderStructure: 'folder-structure',
    docker: 'docker',
    testingPlan: 'testing-plan',
    userStories: 'user-stories',
    roadmap: 'roadmap',
    deploymentGuide: 'deployment-guide',
    costEstimation: 'cost-estimation',
    projectTimeline: 'project-timeline',
    riskAnalysis: 'risk-analysis',
    finalMarkdown: 'final-documentation'
  };
  return names[artifactType] || artifactType;
}

export async function exportToGithub(
  state: ProjectState,
  title: string,
  accessToken: string,
  isPrivate: boolean = true,
  logSummary: any = {},
  onProgress?: (msg: string) => void,
  existingRepoName?: string,
  dirtyArtifacts?: string[]
) {
  const startTime = Date.now();
  console.log(`[GITHUB] Export Started`);
  onProgress?.('Initializing GitHub export...');

  if (!accessToken) {
    console.error(`[GITHUB] Credentials missing. Export Failed.`);
    logSummary.GitHub = 'FAILED';
    return null;
  }

  const octokit = getGithubClient(accessToken);
  let repoData = null;
  let owner = '';
  let repo = '';

  if (existingRepoName) {
    onProgress?.('Fetching existing repository...');
    const [existingOwner, existingRepo] = existingRepoName.split('/');
    owner = existingOwner;
    repo = existingRepo;
    try {
      const { data } = await octokit.repos.get({ owner, repo });
      repoData = data;
      console.log(`[GITHUB] Using existing repository: ${existingRepoName}`);
    } catch (err: any) {
      if (err.status === 401) {
        throw new Error('AUTH_ERROR');
      }
      console.error(`[GITHUB] Failed to fetch existing repo ${existingRepoName}`, err);
      logSummary.GitHub = 'FAILED';
      return null;
    }
  } else {
    // 1. Create Repository
    const baseRepoName = toKebabCase(title || 'new-project');
    let repoName = baseRepoName;
    onProgress?.('Creating repository...');
    
    let attempt = 0;
    while (!repoData && attempt < 10) {
      try {
        const { data } = await octokit.repos.createForAuthenticatedUser({
          name: repoName,
          private: isPrivate,
          auto_init: true,
        });
        repoData = data;
        owner = repoData.owner.login;
        repo = repoData.name;
        console.log(`[GITHUB] Repository Created: ${repoName}`);
      } catch (err: any) {
        if (err.status === 401) {
          throw new Error('AUTH_ERROR');
        }
        // 422 often indicates "name already exists on this account"
        if (err.status === 422) {
          attempt++;
          repoName = `${baseRepoName}-${attempt}`;
        } else {
          console.error(`[GITHUB] Repository creation failed.`, err.response?.data || err.message || err);
          logSummary.GitHub = 'FAILED';
          return null;
        }
      }
    }

    if (!repoData) {
      console.error(`[GITHUB] Failed to create GitHub repository.`);
      logSummary.GitHub = 'FAILED';
      return null;
    }
  }

  // 2. Prepare Tree Nodes
  const treeNodes: { path: string, mode: "100644", type: "blob", content: string }[] = [];

  // A. Add Root files
  if (state.artifacts.markdown?.content) {
    treeNodes.push({ path: 'README.md', mode: "100644", type: "blob", content: state.artifacts.markdown.content });
  } else {
    treeNodes.push({ path: 'README.md', mode: "100644", type: "blob", content: `# ${title}\n\nGenerated by ProdMate.` });
  }

  treeNodes.push({ path: '.gitignore', mode: "100644", type: "blob", content: 'node_modules/\n.env\ndist/\nbuild/\n.DS_Store\n' });
  treeNodes.push({ path: '.env.example', mode: "100644", type: "blob", content: '# Environment Variables\n' });
  
  const licenseText = `MIT License

Copyright (c) ${new Date().getFullYear()} ${owner}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;
  treeNodes.push({ path: 'LICENSE', mode: "100644", type: "blob", content: licenseText });

  if (state.artifacts.docker?.content) {
    // Strip markdown blocks if any
    let dockerContent = state.artifacts.docker.content;
    const blockMatch = dockerContent.match(/```(?:yaml|yml)?\s*([\s\S]*?)\s*```/);
    if (blockMatch) dockerContent = blockMatch[1];
    treeNodes.push({ path: 'docker-compose.yml', mode: "100644", type: "blob", content: dockerContent });
  }

  // B. Skip Document Artifacts (as requested, only storing folder structure)

  // C. Add Folder Structure from structuredData
  if (state.artifacts.folderStructure?.structuredData && Array.isArray(state.artifacts.folderStructure.structuredData)) {
    for (const item of state.artifacts.folderStructure.structuredData) {
      if (item.type === 'directory') {
        treeNodes.push({ path: `${item.path}/.gitkeep`, mode: "100644", type: "blob", content: '' });
      } else if (item.type === 'file') {
        // Only create if we didn't already create it (e.g., README.md, docker-compose.yml, package.json might be in the list, but they are just empty files here for scaffolding)
        // Wait, if it's a file, let's just make it empty for scaffolding. If we already pushed it, GitHub API tree allows overriding/replacing but we shouldn't have duplicate paths in the array.
        // Let's filter duplicates.
        if (!treeNodes.some(n => n.path === item.path)) {
          treeNodes.push({ path: item.path, mode: "100644", type: "blob", content: '' });
        }
      }
    }
  }

  // D. Add .ProdMate Metadata
  treeNodes.push({ path: '.ProdMate/project.json', mode: "100644", type: "blob", content: JSON.stringify({ title, description: state.projectDescription, createdAt: state.createdAt }, null, 2) });
  treeNodes.push({ path: '.ProdMate/artifacts.json', mode: "100644", type: "blob", content: JSON.stringify(Object.keys(state.artifacts), null, 2) });
  treeNodes.push({ path: '.ProdMate/generation.json', mode: "100644", type: "blob", content: JSON.stringify({ sessionId: state.sessionId, tokens: state.totalTokensUsed }, null, 2) });

  // 3. Create Tree
  onProgress?.('Uploading files...');
  const uniquePaths = new Set<string>();
  const filteredTreeNodes = [];
  for (const node of treeNodes) {
    if (!uniquePaths.has(node.path)) {
      uniquePaths.add(node.path);
      filteredTreeNodes.push(node);
    }
  }

  // Wait a moment for GitHub to initialize the repo (auto_init takes a few ms)
  await new Promise(resolve => setTimeout(resolve, 1000));

  // Get the initial commit
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: 'heads/main',
  });
  const commitSha = refData.object.sha;

  const { data: initialCommitData } = await octokit.git.getCommit({
    owner,
    repo,
    commit_sha: commitSha,
  });
  const baseTreeSha = initialCommitData.tree.sha;

  const { data: treeData } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseTreeSha,
    tree: filteredTreeNodes as any, // type assertion for mode
  });

  // 4. Create Commit
  let commitMessage = 'Initial project scaffold generated by ProdMate';
  if (existingRepoName && dirtyArtifacts && dirtyArtifacts.length > 0) {
    const formatArtifactNames = (artifacts: string[]) => {
      const formatted = artifacts.map(a => getFileNameForArtifact(a as ArtifactType));
      if (formatted.length === 1) return formatted[0];
      if (formatted.length === 2) return `${formatted[0]} and ${formatted[1]}`;
      return `${formatted.slice(0, -1).join(', ')}, and ${formatted[formatted.length - 1]}`;
    };
    
    // Categorize prefix based on primary artifact
    let prefix = 'chore(sync)';
    if (dirtyArtifacts.includes('apiDesign') || dirtyArtifacts.includes('db') || dirtyArtifacts.includes('architecture')) prefix = 'feat(sync)';
    else if (dirtyArtifacts.includes('markdown') || dirtyArtifacts.includes('deploymentGuide')) prefix = 'docs(sync)';
    
    commitMessage = `${prefix}: update ${formatArtifactNames(dirtyArtifacts)}`;
  }

  onProgress?.('Creating commit...');
  const { data: commitData } = await octokit.git.createCommit({
    owner,
    repo,
    message: commitMessage,
    tree: treeData.sha,
    parents: [commitSha],
  });

  // 5. Update Reference (update main branch)
  onProgress?.('Finalizing repository...');
  await octokit.git.updateRef({
    owner,
    repo,
    ref: 'heads/main',
    sha: commitData.sha,
  });

  console.log(`[GITHUB] Scaffolding Pushed`);
  const duration = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(`[GITHUB] Export Completed (${duration}s)`);
  logSummary.GitHub = 'SUCCESS';
  onProgress?.('Repository ready.');

  return {
    githubUrl: repoData.html_url,
    githubRepository: repoData.full_name,
    githubRepositoryId: repoData.id.toString(),
    githubOwner: owner,
    githubDefaultBranch: repoData.default_branch,
    githubLastCommitSha: commitData.sha,
  };
}
