import { getNotionClient } from './client';
import { markdownToBlocks } from './converter';
import type { ProjectState, ArtifactType } from '@/lib/pipeline/types';
import { parse } from 'yaml';
import { BlockObjectRequest } from '@notionhq/client/build/src/api-endpoints';

async function retryNotionCall<T>(apiCall: () => Promise<T>, maxRetries = 5): Promise<T> {
  let attempt = 0;
  while (attempt < maxRetries) {
    try {
      return await apiCall();
    } catch (err: unknown) {
      const error = err as { status?: number, headers?: { get?: (key: string) => string | null } | Record<string, string | string[]> };
      if (error?.status === 429 && attempt < maxRetries - 1) {
        let retryAfter: string | null = null;
        const headers = error.headers;
        if (headers) {
          if ('get' in headers && typeof headers.get === 'function') {
            retryAfter = headers.get('retry-after');
          } else if ('retry-after' in headers && typeof (headers as Record<string, string>)['retry-after'] === 'string') {
            retryAfter = (headers as Record<string, string>)['retry-after'];
          }
        }
        const delay = retryAfter ? parseInt(retryAfter, 10) * 1000 : Math.pow(2, attempt) * 1000;
        await new Promise(resolve => setTimeout(resolve, delay));
        attempt++;
      } else {
        throw err;
      }
    }
  }
  throw new Error("Max retries exceeded");
}

export async function exportToNotion(state: ProjectState, title: string, accessToken: string, rootPageId: string) {
  if (!rootPageId || !accessToken) {
    console.error('Notion credentials or root page ID missing.');
    return null;
  }

  const notion = getNotionClient(accessToken);

  try {
    const parentChildren: BlockObjectRequest[] = [
      {
        object: 'block',
        type: 'heading_2',
        heading_2: { rich_text: [{ type: 'text', text: { content: '📁 Project Overview' } }] }
      },
      {
        object: 'block',
        type: 'paragraph',
        paragraph: { rich_text: [{ type: 'text', text: { content: `🏷️ Project Name: ${title || 'New Project'}` } }] }
      },
      {
        object: 'block',
        type: 'paragraph',
        paragraph: { rich_text: [{ type: 'text', text: { content: `⏱️ Generation Timestamp: ${new Date().toISOString()}` } }] }
      },
      {
        object: 'block',
        type: 'paragraph',
        paragraph: { rich_text: [{ type: 'text', text: { content: '🚀 Generated by EdgeOS' } }] }
      },
      {
        object: 'block',
        type: 'paragraph',
        paragraph: { rich_text: [{ type: 'text', text: { content: `📄 Artifacts Count: ${Object.keys(state.artifacts).length}` } }] }
      }
    ];

    let hasTechStack = false;
    const configContent = state.artifacts.config?.content;
    if (configContent) {
      try {
        const parsed = parse(configContent);
        let techStackList: string[] = [];
        if (Array.isArray(parsed?.techStack)) techStackList = parsed.techStack;
        else if (Array.isArray(parsed?.technologies)) techStackList = parsed.technologies;
        else if (Array.isArray(parsed?.stack)) techStackList = parsed.stack;
        else if (parsed?.techStack && typeof parsed.techStack === 'object') {
           techStackList = Object.values(parsed.techStack).flat().filter(x => typeof x === 'string') as string[];
        }

        if (techStackList.length > 0) {
          parentChildren.push({
            object: 'block',
            type: 'paragraph',
            paragraph: { rich_text: [{ type: 'text', text: { content: '💻 Detected Tech Stack:' } }] }
          });
          techStackList.forEach((item: string) => {
            parentChildren.push({
              object: 'block',
              type: 'bulleted_list_item',
              bulleted_list_item: { rich_text: [{ type: 'text', text: { content: String(item) } }] }
            });
          });
          hasTechStack = true;
        }
      } catch (err) {
        console.error("YAML Parse error", err);
      }
    }

    if (!hasTechStack) {
      parentChildren.push({
        object: 'block',
        type: 'paragraph',
        paragraph: { rich_text: [{ type: 'text', text: { content: '💻 Detected Tech Stack: Based on generated configuration.' } }] }
      });
    }

    parentChildren.push({
      object: 'block',
      type: 'divider',
      divider: {}
    });

    let parentPage;
    try {
      parentPage = await retryNotionCall(() => notion.pages.create({
        parent: { page_id: rootPageId },
        properties: {
          title: {
            title: [
              {
                text: { content: `✨ ${title || 'New Project'}` }
              }
            ]
          }
        },
        children: parentChildren
      }));
    } catch (e: any) {
      if (e.code === 'object_not_found') {
        throw new Error('PARENT_PAGE_NOT_FOUND');
      }
      throw e;
    }

    const parentId = parentPage.id;
    const parentUrl = ('url' in parentPage && typeof parentPage.url === 'string') ? parentPage.url : `https://notion.so/${parentId.replace(/-/g, '')}`;

    const orderedTypes: ArtifactType[] = [
      'markdown', 'config', 'db', 'apiDesign', 'docker', 'folderStructure', 
      'testingPlan', 'userStories', 'roadmap', 'deploymentGuide', 
      'costEstimation', 'projectTimeline', 'riskAnalysis', 'finalMarkdown'
    ];

    const artifactMeta: Record<string, { name: string, emoji: string }> = {
      markdown: { name: 'README', emoji: '📘' },
      config: { name: 'Config', emoji: '⚙️' },
      db: { name: 'Database Schema', emoji: '🗄️' },
      apiDesign: { name: 'API Design', emoji: '🌐' },
      docker: { name: 'Docker', emoji: '🐳' },
      folderStructure: { name: 'Folder Structure', emoji: '📁' },
      testingPlan: { name: 'Testing Plan', emoji: '🧪' },
      userStories: { name: 'User Stories', emoji: '👥' },
      roadmap: { name: 'Roadmap', emoji: '🛣️' },
      deploymentGuide: { name: 'Deployment Guide', emoji: '🚀' },
      costEstimation: { name: 'Cost Estimation', emoji: '💰' },
      projectTimeline: { name: 'Timeline', emoji: '📅' },
      riskAnalysis: { name: 'Risk Analysis', emoji: '⚠️' },
      finalMarkdown: { name: 'Final Documentation', emoji: '📄' }
    };

    const artifactsToExport: { type: string; content: string }[] = [];
    
    for (const type of orderedTypes) {
      if (state.artifacts[type]?.content) {
        artifactsToExport.push({ type, content: state.artifacts[type].content });
      }
    }
    
    const exportedTypes = new Set(artifactsToExport.map(a => a.type));
    for (const [type, artifact] of Object.entries(state.artifacts)) {
      if (!exportedTypes.has(type) && artifact?.content) {
        artifactsToExport.push({ type, content: artifact.content });
      }
    }

    for (const { type, content } of artifactsToExport) {
      const allBlocks = markdownToBlocks(content);
      const firstChunk = allBlocks.slice(0, 100);

      const meta = artifactMeta[type] || { name: type.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()).trim(), emoji: '📄' };

      try {
        const childPage = await retryNotionCall(() => notion.pages.create({
          parent: { page_id: parentId },
          properties: {
            title: {
              title: [{ text: { content: `${meta.emoji} ${meta.name}` } }]
            }
          },
          children: firstChunk
        }));

        let remaining = allBlocks.slice(100);
        while (remaining.length > 0) {
          const chunk = remaining.slice(0, 100);
          await retryNotionCall(() => notion.blocks.children.append({
            block_id: childPage.id,
            children: chunk
          }));
          remaining = remaining.slice(100);
        }
      } catch (err) {
        console.error(`Failed to export artifact ${type} to Notion:`, err);
      }
    }

    return { notionPageId: parentId, notionUrl: parentUrl };
  } catch (err) {
    console.error('Failed to create Notion parent page:', err);
    return null;
  }
}
