import { ProjectState } from '../pipeline/types';
import { db } from '../firebase-admin';
import { callGroqRaw, createCallConfig } from '../pipeline/GroqClient';

export async function exportToGmail(
  state: ProjectState,
  title: string,
  userId: string,
  accessToken: string,
  recipient: string,
  template: string,
  logSummary: any,
  onProgress: (msg: string) => Promise<void>
) {
  try {
    await onProgress(`Generating ${template} email draft...`);

    const prompt = `
You are an AI assistant. I need you to draft a professional email.
Project Title: ${title}
Template: ${template}
Recipient: ${recipient}

CONTEXT:
Summary: ${state.projectSummary || ''}
Timeline: ${state.artifacts['projectTimeline']?.content || ''}
Roadmap: ${state.artifacts['roadmap']?.content || ''}
Cost Estimation: ${state.artifacts['costEstimation']?.content || ''}
GitHub: ${state.githubUrl || 'Not setup'}
Jira: ${state.jiraUrl || 'Not setup'}
Notion: ${state.notionUrl || 'Not setup'}

Depending on the template, draft an appropriate, highly professional email using the provided context.
- If "proposal": Focus on the summary, roadmap, and cost estimation to pitch the project.
- If "weekly": Focus on the timeline progress and link to GitHub/Jira/Notion.
- If "delivery": Focus on completion, linking the repositories and documentation.

Return ONLY a JSON object in this format:
{
  "subject": "Email Subject Line",
  "body": "The plain text body of the email. Do not use markdown."
}
No markdown wrapping, just the raw JSON object.
`;

    const groqKey = process.env.GROQ_API_KEY;
    if (!groqKey) throw new Error('GROQ_API_KEY is not set');

    const config = createCallConfig(groqKey, 1024, 0.2);
    const res = await callGroqRaw(
      config,
      [{ role: 'user', content: prompt }],
      'GenerateEmailDraft'
    );

    if (!res || !res.content) throw new Error(`Groq API error`);
    const rawOutput = res.content;
    
    let draftContent = null;
    try {
      draftContent = JSON.parse(rawOutput);
    } catch (e) {
      console.error('Failed to parse Gemini output:', rawOutput);
      throw new Error('Failed to parse email draft from AI output.');
    }

    if (!draftContent || !draftContent.subject || !draftContent.body) {
      throw new Error('Invalid email draft generated by AI.');
    }

    await onProgress(`Creating draft in Gmail...`);

    // Gmail API requires RFC 2822 formatted message encoded in base64url
    const rawMessage = [
      `To: ${recipient}`,
      `Subject: ${draftContent.subject}`,
      `Content-Type: text/plain; charset="UTF-8"`,
      '',
      draftContent.body
    ].join('\r\n');

    const encodedMessage = Buffer.from(rawMessage).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

    const draftRes = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/drafts', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        message: {
          raw: encodedMessage
        }
      })
    });

    if (!draftRes.ok) {
      throw new Error(`Gmail API error: ${await draftRes.text()}`);
    }

    const draftData = await draftRes.json();
    
    const userRef = db.collection('user_integrations').doc(userId);
    await userRef.set({
      gmail: {
        draftId: draftData.id,
        recipient,
        template,
        updatedAt: new Date().toISOString()
      }
    }, { merge: true });

    return {
      draftUrl: `https://mail.google.com/mail/u/0/#drafts`
    };
  } catch (error: any) {
    console.error('Gmail export error:', error);
    return null;
  }
}
